name: build-and-test
on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out docker-slim/docker-slim repo
        uses: actions/checkout@v3

      - name: Set up Go development environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.15.0'

      - name: Build DockerSlim (multi-arch)
        run: make build

      - name: Upload docker-slim binaries (Linux, amd64)
        uses: actions/upload-artifact@v3
        with:
          name: dist_linux
          path: dist_linux
          retention-days: 1

      - name: Upload docker-slim binaries (Linux, arm64)
        uses: actions/upload-artifact@v3
        with:
          name: dist_linux_arm64
          path: dist_linux_arm64
          retention-days: 1

      - name: Upload docker-slim binaries (Linux, arm)
        uses: actions/upload-artifact@v3
        with:
          name: dist_linux_arm
          path: dist_linux_arm
          retention-days: 1

      - name: Upload docker-slim binaries (macOS, amd64)
        uses: actions/upload-artifact@v3
        with:
          name: dist_mac
          path: dist_mac
          retention-days: 1

  test:
    needs: build
    strategy:
      matrix:
        os:
          # macos runners don't support docker yet
          - ubuntu-latest
        suite:
          - compose
          - distroless
          - dotnet
          - elixir
          - golang
          - java
          - node
          - php
          - python
          - ruby
          - rust
        include:
          - os: ubuntu-latest
            bin_artifacts: dist_linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out docker-slim/docker-slim repo
        uses: actions/checkout@v3

      - name: Check out docker-slim/examples repo
        uses: actions/checkout@v3
        with:
          repository: docker-slim/examples
          path: e2e

      - name: Download docker-slim binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.bin_artifacts }}
          path: bin

      - name: Fix docker-slim binaries permissions
        run: chmod a+x bin/*

      - name: Add docker-slim/bin folder to $PATH
        run: echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Run all e2e tests from docker-slim/examples
        run: DSLIM_EXAMPLES_DIR=e2e make test-e2e-${{ matrix.suite }}
